import Head from 'next/head'

export default function Home() {  
  return (
    <div>
      <Head>
        <title>IDA Digital Design</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full flex flex-col justify-center items-center gap-2" style={{height: `calc(100vh - 3.5rem)`}}>
        <h1>Final Project</h1>
        <a href="https://recapmymusic.netlify.app/" target="_blank" rel="noreferrer" className="underline text-white text-3xl">RECAP_MY_MUSIC</a>
      </div>
    </div>
  )
}
